parameters:
    #admin_path: control_panel

knp_disqus:
    api_key: %knp_disqus.api_key%
    secret_key: %knp_disqus.secret_key% # optional, for SSO auth only
    forums:
        lorem:
            shortname: "dmitryxepersonalblog"
            cache: my_cache_for_lorem # cache template key, usage described below
        ipsum:
            shortname: "amet"
